#!/bin/bash


echo "bender 2025 repo is setup"

echo "BENDER_HOSTNAME = $BENDER_HOSTNAME"
echo "BENDER_DIR = $BENDER_DIR"
echo "BENDER_SCRIPTS_DIR = $BENDER_SCRIPTS_DIR"
echo "BENDER_DEPENDENCIES_DIR = $BENDER_DEPENDENCIES_DIR"
echo "BENDER_BIN_DIR = $BENDER_BIN_DIR"
